from dataclasses import dataclass
from typing import Optional, Protocol, List, Dict, Any
from neuralresearcher.config import Config
from neuralresearcher.state import (
    TopicSpec, Paper, Claim, Gap, Direction, ResearchPlan, PlanStep, CoverageReport, ReviewResult
)

class StoreProtocol(Protocol):
    def load_topic_spec(self) -> Optional[TopicSpec]: ...
    def save_topic_spec(self, topic_spec: TopicSpec) -> None: ...
    def load_papers(self) -> List[Paper]: ...
    def save_papers(self, papers: List[Paper]) -> None: ...
    def update_papers(self, updated_papers: List[Paper]) -> None: ...
    def load_claims(self) -> List[Claim]: ...
    def save_claims(self, claims: List[Claim]) -> None: ...
    def load_gaps(self) -> List[Gap]: ...
    def save_gaps(self, gaps: List[Gap]) -> None: ...
    def load_directions(self) -> List[Direction]: ...
    def save_directions(self, directions: List[Direction]) -> None: ...
    def load_plan(self) -> tuple[Optional[ResearchPlan], List[PlanStep]]: ...
    def save_plan(self, plan: ResearchPlan, steps: List[PlanStep]) -> None: ...
    def load_coverage_report(self) -> Optional[CoverageReport]: ...
    def save_coverage_report(self, report: CoverageReport) -> None: ...
    def load_review_result(self) -> Optional[ReviewResult]: ...
    def save_review_result(self, result: ReviewResult) -> None: ...
    def save_transcript(self, task_id: str, agent_name: str, messages: List[Dict[str, Any]], usage: Dict[str, Any], assistant_response: Optional[Dict[str, Any]] = None) -> None: ...
    def load_transcripts(self, task_id: str) -> List[Dict[str, Any]]: ...


@dataclass
class AgentContext:
    """Explicit context passed to each agent, replacing the orchestrator God object."""
    store: StoreProtocol
    config: Config
    topic: str
    task_id: str = "default_run"
    review_feedback: Optional[str] = None
